zeros:
  joint1: 0.0
  joint2: 0.0
  joint3: 0.0
  joint4: 0.0
  joint5: 0.0
  joint6: 0.0
link_lengths:
  l1: 0.1
  l2: 2.5
  l3: 2.5
  l4: 0.0
  l5: 0.0
  l6: 0.0
ball_start:
  x: 5.0
  y: 2.0
  z: 0.0
ball_vel:
  x: -1.0
  y: -0.2
  z: 0.35
trajectory_type:
  alpha: 0.0
source_list:
  ["pubJointStates"]
